-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.usuarios
(
    id serial NOT NULL,
    cedula bigint NOT NULL,
    nombre character varying(100),
    correo character varying(100) NOT NULL,
    contrasena character varying(50) NOT NULL,
    fecha timestamp with time zone NOT NULL,
    activo boolean,
    bloqueado boolean,
    PRIMARY KEY (cedula)
);

CREATE TABLE IF NOT EXISTS public.clientes
(
    id serial NOT NULL,
    nit bigint NOT NULL,
    razon_social character varying(100) NOT NULL,
    activo boolean NOT NULL,
    telefono character varying(50),
    direccion character varying(120),
    correo character varying(100),
    fecha timestamp with time zone,
    PRIMARY KEY (nit)
);

CREATE TABLE IF NOT EXISTS public.clientes_usuarios
(
    id serial NOT NULL,
    cliente_nit bigint NOT NULL,
    usuario_cedula bigint NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.permisos_acciones
(
    id serial NOT NULL,
    id_permiso character varying(20) NOT NULL,
    nombre character varying(50) NOT NULL,
    PRIMARY KEY (id_permiso)
);

CREATE TABLE IF NOT EXISTS public.usuarios_permisos_acciones
(
    id serial NOT NULL,
    cedula_usuario bigint NOT NULL,
    permiso_id_accion character varying(20) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.permisos_modulos
(
    id serial NOT NULL,
    id_modulo character varying(20) NOT NULL,
    nombre_modulo character varying(50) NOT NULL,
    PRIMARY KEY (id_modulo)
);

CREATE TABLE IF NOT EXISTS public.usuarios_permisos_modulos
(
    id serial NOT NULL,
    cedula_usuario bigint NOT NULL,
    modulo_id "char" NOT NULL,
    PRIMARY KEY (id)
);

ALTER TABLE public.clientes_usuarios
    ADD FOREIGN KEY (cliente_nit)
    REFERENCES public.clientes (nit)
    NOT VALID;


ALTER TABLE public.clientes_usuarios
    ADD FOREIGN KEY (usuario_cedula)
    REFERENCES public.usuarios (cedula)
    NOT VALID;


ALTER TABLE public.usuarios_permisos_acciones
    ADD FOREIGN KEY (cedula_usuario)
    REFERENCES public.usuarios (cedula)
    NOT VALID;


ALTER TABLE public.usuarios_permisos_acciones
    ADD FOREIGN KEY (permiso_id_accion)
    REFERENCES public.permisos_acciones (id_permiso)
    NOT VALID;


ALTER TABLE public.usuarios_permisos_modulos
    ADD FOREIGN KEY (cedula_usuario)
    REFERENCES public.usuarios (cedula)
    NOT VALID;


ALTER TABLE public.usuarios_permisos_modulos
    ADD FOREIGN KEY (modulo_id)
    REFERENCES public.permisos_modulos (id_modulo)
    NOT VALID;

END;